"""Worldwide-remote roles open to India-based candidates with high pay.

Selection criteria:
  - Company hires globally / EOR / contractor in India OR has remote-India listings
  - Comp band typically USD 70k-180k base (= INR 60L-1.5Cr+ at 2026 rates)
  - Stack overlaps with MLOps / observability / ML infra
  - Verified active in April 2026

`comp_band_inr` is approximate, full base only (excl. equity/bonus). Always verify
on the live JD; many of these roles localize down to country pay bands.
"""

JOBS_REMOTE_GLOBAL = [
    # ============================================================
    # HIGH PROBABILITY — direct MLOps / observability fits
    # ============================================================
    {
        "company": "Grafana Labs",
        "role": "Software Engineer / SRE / Solutions Engineer (APAC remote)",
        "category": "Remote-First (Observability)",
        "location": "Remote — APAC / India",
        "experience": "2-4 yrs",
        "key_requirements": "Go/Python, Prometheus, Grafana, Loki, Tempo, Kubernetes",
        "why_fit": "PERFECT match. Your daily stack at Zzazz IS the Grafana product. Fully remote-first; 147+ open roles.",
        "fit_score": 92,
        "priority": "High",
        "comp_band_inr": "INR 50-90 LPA",
        "primary_link": "https://grafana.com/careers/",
        "search_link": "https://job-boards.greenhouse.io/grafanalabs",
    },
    {
        "company": "Weights & Biases (CoreWeave)",
        "role": "ML Engineer / MLOps Engineer (Remote)",
        "category": "Remote-First (MLOps)",
        "location": "Remote — global",
        "experience": "2-4 yrs",
        "key_requirements": "Python, PyTorch/TF, model tracking, experiment infra",
        "why_fit": "MLOps tooling company. Your MLflow + observability + shadow-deploy work maps directly to their product surface.",
        "fit_score": 88,
        "priority": "High",
        "comp_band_inr": "INR 60-100 LPA",
        "primary_link": "https://wandb.ai/site/careers",
        "search_link": "https://job-boards.greenhouse.io/weightsandbiases",
    },
    {
        "company": "Hugging Face",
        "role": "ML Engineer / Inference Infra Engineer (Remote)",
        "category": "Remote-First (AI Infra)",
        "location": "Remote — global (incl. India)",
        "experience": "2-4 yrs",
        "key_requirements": "Python, PyTorch, model serving (Triton/TGI/vLLM), Kubernetes",
        "why_fit": "Your ONNX + DistilUSE + GPU-to-CPU optimization work is directly relevant to TGI/inference endpoints.",
        "fit_score": 85,
        "priority": "High",
        "comp_band_inr": "INR 70-130 LPA",
        "primary_link": "https://huggingface.co/jobs",
        "search_link": "https://apply.workable.com/huggingface/",
    },
    {
        "company": "Modal Labs",
        "role": "Software Engineer / ML Infra (Remote)",
        "category": "Remote-First (ML Infra)",
        "location": "Remote — global",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Rust/Go, Kubernetes, container runtimes, distributed systems",
        "why_fit": "Serverless compute for ML; your K8s + container + scaling work matches. Bar is high but stack-perfect.",
        "fit_score": 82,
        "priority": "High",
        "comp_band_inr": "INR 80-140 LPA",
        "primary_link": "https://modal.com/careers",
        "search_link": "https://job-boards.greenhouse.io/modallabs",
    },
    {
        "company": "Anyscale",
        "role": "Software Engineer (Ray / Distributed Systems)",
        "category": "Remote-First (ML Infra)",
        "location": "Remote — global / select countries",
        "experience": "2-4 yrs",
        "key_requirements": "Python/C++, distributed systems, Kubernetes, Ray",
        "why_fit": "Distributed ML compute; your scale + serving work is a fit. India remote viability varies — check JD.",
        "fit_score": 78,
        "priority": "High",
        "comp_band_inr": "INR 70-130 LPA",
        "primary_link": "https://www.anyscale.com/careers",
        "search_link": "https://job-boards.greenhouse.io/anyscale",
    },
    {
        "company": "Databricks India / Remote",
        "role": "Software Engineer / MLOps Engineer (MLflow team)",
        "category": "Remote-Hybrid (Data/ML Platform)",
        "location": "Bangalore / Remote-India",
        "experience": "2-5 yrs",
        "key_requirements": "Python/Scala, Spark, MLflow, Kubernetes",
        "why_fit": "You actively use MLflow. Direct stack match. Pay is among the highest in India.",
        "fit_score": 85,
        "priority": "High",
        "comp_band_inr": "INR 50-100 LPA",
        "primary_link": "https://www.databricks.com/company/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops%20OR%20mlflow&f_C=4806458",
    },
    {
        "company": "Confluent",
        "role": "Software Engineer (Streaming / Kafka)",
        "category": "Remote-Hybrid (Data Streaming)",
        "location": "Bangalore / Remote-India",
        "experience": "2-4 yrs",
        "key_requirements": "Java/Go/Python, Kafka, distributed systems, Kubernetes",
        "why_fit": "Your Kafka/Redpanda experience transfers cleanly. Hires aggressively in India.",
        "fit_score": 80,
        "priority": "High",
        "comp_band_inr": "INR 50-100 LPA",
        "primary_link": "https://careers.confluent.io/jobs",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=10995607",
    },
    {
        "company": "MongoDB",
        "role": "Software Engineer II (Atlas / Serverless / Search)",
        "category": "Remote-Hybrid (Data Platform)",
        "location": "Gurgaon / Remote-India",
        "experience": "2-4 yrs",
        "key_requirements": "C++/Java/Python, distributed systems, Kubernetes",
        "why_fit": "Your MongoDB experience + distributed-systems work fits. Strong India hiring.",
        "fit_score": 75,
        "priority": "High",
        "comp_band_inr": "INR 45-90 LPA",
        "primary_link": "https://www.mongodb.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=2299890",
    },

    # ============================================================
    # MEDIUM PROBABILITY — strong but bar is higher / India unclear
    # ============================================================
    {
        "company": "GitLab",
        "role": "Backend Engineer / Site Reliability Engineer (Remote)",
        "category": "Remote-First (Dev Tools)",
        "location": "Remote — India eligible",
        "experience": "2-4 yrs",
        "key_requirements": "Ruby/Go/Python, Kubernetes, observability, distributed systems",
        "why_fit": "All-remote since founding. SRE/observability profile directly applies. Pay localized but solid.",
        "fit_score": 78,
        "priority": "Medium",
        "comp_band_inr": "INR 40-80 LPA",
        "primary_link": "https://about.gitlab.com/jobs/",
        "search_link": "https://job-boards.greenhouse.io/gitlab",
    },
    {
        "company": "Cloudflare India",
        "role": "Systems Engineer / Backend Engineer (Workers AI / ML)",
        "category": "Remote-Hybrid (Infra)",
        "location": "Bangalore / Remote-India",
        "experience": "2-4 yrs",
        "key_requirements": "Go/Rust/Python, Kubernetes, networking, ML inference (Workers AI)",
        "why_fit": "Workers AI = inference at edge; your inference optimization story fits well. Hires India remote.",
        "fit_score": 76,
        "priority": "Medium",
        "comp_band_inr": "INR 50-100 LPA",
        "primary_link": "https://www.cloudflare.com/careers/jobs/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=systems%20engineer&f_C=10215",
    },
    {
        "company": "Datadog",
        "role": "Software Engineer (Observability / ML)",
        "category": "Remote-Hybrid (Observability)",
        "location": "Remote-India / NY hybrid",
        "experience": "2-4 yrs",
        "key_requirements": "Go/Python, Kafka, distributed systems, observability",
        "why_fit": "Your observability work is a direct sell. India hiring is patchy but possible via remote.",
        "fit_score": 74,
        "priority": "Medium",
        "comp_band_inr": "INR 60-110 LPA",
        "primary_link": "https://careers.datadoghq.com/all-jobs/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=2832720",
    },
    {
        "company": "Snowflake India",
        "role": "Software Engineer (Cortex AI / Data Platform)",
        "category": "Remote-Hybrid (Data Platform)",
        "location": "Pune / Bangalore / Remote-India",
        "experience": "2-4 yrs",
        "key_requirements": "C++/Java/Python, distributed systems, ML inference",
        "why_fit": "Cortex AI ML platform team is growing. Your inference + scale background fits.",
        "fit_score": 72,
        "priority": "Medium",
        "comp_band_inr": "INR 50-100 LPA",
        "primary_link": "https://careers.snowflake.com/us/en",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=2330523",
    },
    {
        "company": "Pinecone",
        "role": "ML / Backend Engineer (Vector DB)",
        "category": "Remote-First (AI Infra)",
        "location": "Remote — global / India eligibility varies",
        "experience": "2-4 yrs",
        "key_requirements": "Rust/Go/Python, distributed systems, vector search",
        "why_fit": "Vector DB infra; your distributed ML serving experience is relevant. Bar is high.",
        "fit_score": 70,
        "priority": "Medium",
        "comp_band_inr": "INR 70-120 LPA",
        "primary_link": "https://www.pinecone.io/careers/",
        "search_link": "https://job-boards.greenhouse.io/pinecone",
    },
    {
        "company": "ClearML / Allegro AI",
        "role": "MLOps Engineer / Backend Engineer (Remote)",
        "category": "Remote-First (MLOps)",
        "location": "Remote — global",
        "experience": "2-4 yrs",
        "key_requirements": "Python, Kubernetes, ML pipelines, experiment tracking",
        "why_fit": "MLOps platform startup. Direct stack overlap; smaller team = senior leverage.",
        "fit_score": 75,
        "priority": "Medium",
        "comp_band_inr": "INR 50-90 LPA",
        "primary_link": "https://clear.ml/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops&f_C=14491625",
    },
    {
        "company": "Iterative.ai (DVC / CML)",
        "role": "ML Engineer / DevOps Engineer (Remote)",
        "category": "Remote-First (MLOps)",
        "location": "Remote — global",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Go, Git, CI/CD, ML pipelines",
        "why_fit": "DVC is widely used in MLOps stacks. Your GitLab CI + ML pipeline work is directly relevant.",
        "fit_score": 74,
        "priority": "Medium",
        "comp_band_inr": "INR 45-80 LPA",
        "primary_link": "https://iterative.ai/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=42572005",
    },
    {
        "company": "Vercel",
        "role": "Software Engineer / Infrastructure Engineer (Remote)",
        "category": "Remote-First (Dev Infra)",
        "location": "Remote — APAC / India eligibility varies",
        "experience": "2-4 yrs",
        "key_requirements": "TypeScript/Go/Rust, Kubernetes, edge infra",
        "why_fit": "Backend/infra fit. ML adjacency lower; brand value high. India remote viability varies.",
        "fit_score": 68,
        "priority": "Medium",
        "comp_band_inr": "INR 60-110 LPA",
        "primary_link": "https://vercel.com/careers",
        "search_link": "https://job-boards.greenhouse.io/vercel",
    },
    {
        "company": "Replicate",
        "role": "ML Infra / Backend Engineer (Remote)",
        "category": "Remote-First (ML Inference)",
        "location": "Remote — global",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Go, Kubernetes, model serving, GPU infra",
        "why_fit": "ML inference platform. Your serving + scaling work is directly relevant.",
        "fit_score": 76,
        "priority": "Medium",
        "comp_band_inr": "INR 60-110 LPA",
        "primary_link": "https://replicate.com/about#jobs",
        "search_link": "https://job-boards.greenhouse.io/replicate",
    },
    {
        "company": "Together AI",
        "role": "ML Infra / Inference Engineer (Remote)",
        "category": "Remote-First (AI Infra)",
        "location": "Remote — global / India eligibility varies",
        "experience": "2-4 yrs",
        "key_requirements": "Python/CUDA, model serving, distributed inference",
        "why_fit": "LLM inference infra. Your serving/optimization story fits, though CUDA depth helps.",
        "fit_score": 70,
        "priority": "Medium",
        "comp_band_inr": "INR 70-130 LPA",
        "primary_link": "https://www.together.ai/careers",
        "search_link": "https://job-boards.greenhouse.io/togetherai",
    },

    # ============================================================
    # STRETCH — top brand or high bar
    # ============================================================
    {
        "company": "Stripe India / Remote",
        "role": "Software Engineer (Backend / ML / Risk Platform)",
        "category": "Remote-Hybrid (Fintech)",
        "location": "Bangalore / Remote-India",
        "experience": "2-4 yrs",
        "key_requirements": "Ruby/Java/Python, distributed systems, fraud ML",
        "why_fit": "Fraud/risk ML at Stripe scale matches your fintech project. Hiring bar very high.",
        "fit_score": 64,
        "priority": "Stretch",
        "comp_band_inr": "INR 70-140 LPA",
        "primary_link": "https://stripe.com/jobs/search?office_locations=India--Bengaluru&office_locations=India--Remote",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=2135371",
    },
    {
        "company": "Anthropic",
        "role": "ML Infra / Software Engineer (Remote)",
        "category": "Remote-Hybrid (AI Frontier)",
        "location": "SF / Remote (limited India)",
        "experience": "2-5 yrs",
        "key_requirements": "Python/Rust, distributed training/inference, GPU infra",
        "why_fit": "Frontier AI lab. India remote rare but pay is top of market. Apply but expect long shot.",
        "fit_score": 55,
        "priority": "Stretch",
        "comp_band_inr": "INR 1.5-3 Cr",
        "primary_link": "https://www.anthropic.com/careers",
        "search_link": "https://job-boards.greenhouse.io/anthropic",
    },
    {
        "company": "OpenAI",
        "role": "ML Infra Engineer / Software Engineer (Remote)",
        "category": "Remote-Hybrid (AI Frontier)",
        "location": "SF / Remote (limited India)",
        "experience": "3-5 yrs",
        "key_requirements": "Python/C++, distributed systems, model serving",
        "why_fit": "Brand stretch. India remote limited; bar very high. Worth applying for the optionality.",
        "fit_score": 52,
        "priority": "Stretch",
        "comp_band_inr": "INR 1.5-3 Cr",
        "primary_link": "https://openai.com/careers/search/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20infra&f_C=11130470",
    },
    {
        "company": "Toptal / Turing (Contract Platforms)",
        "role": "Senior ML Engineer / MLOps Contractor (USD-paid)",
        "category": "Contract Platform",
        "location": "Remote — India eligible",
        "experience": "2-5 yrs",
        "key_requirements": "Python, Kubernetes, MLOps stack, English fluency",
        "why_fit": "Quick-onboarding contractor route. Pay USD/hour. Use as parallel pipeline alongside FT search.",
        "fit_score": 75,
        "priority": "Medium",
        "comp_band_inr": "INR 40-100 LPA equiv (USD/hour)",
        "primary_link": "https://www.turing.com/jobs",
        "search_link": "https://www.toptal.com/talent/apply",
    },
]


def by_priority(priority: str):
    return sorted(
        [j for j in JOBS_REMOTE_GLOBAL if j["priority"] == priority],
        key=lambda j: j["fit_score"],
        reverse=True,
    )


def all_sorted():
    return sorted(JOBS_REMOTE_GLOBAL, key=lambda j: j["fit_score"], reverse=True)
