"""Curated job opportunities for Hitesh's profile (MLOps, 2+ yrs, India).

Each entry is a real, currently-hiring company in April 2026. The `primary_link`
column points to the canonical careers page (stable across role rotations); the
`search_link` column is a LinkedIn pre-filtered search to surface live JDs.

`fit_score` rubric (out of 100):
  85-95 — direct MLOps / ML platform role, 0-3 yrs, India
  75-84 — strong adjacent (ML infra, applied ML, backend on ML team)
  65-74 — good transfer (backend / SRE / data eng with ML adjacency)
  50-64 — stretch (top-tier brand or partial stack overlap)
"""

JOBS = [
    # ============================================================
    # HIGH PROBABILITY — direct MLOps / ML Platform fits (>= 80)
    # ============================================================
    {
        "company": "Razorpay",
        "role": "ML Platform Engineer / MLOps Engineer (I/II)",
        "category": "Scale-up (Fintech)",
        "location": "Bangalore",
        "experience": "1-3 yrs",
        "key_requirements": "Python, Kubernetes, Airflow, MLflow, feature stores, real-time inference",
        "why_fit": "Razorpay's fraud/risk ML stack mirrors your Zzazz work — FastAPI, K8s, Redis, real-time scoring. Direct stack match.",
        "fit_score": 92,
        "priority": "High",
        "primary_link": "https://razorpay.com/jobs/jobs-all/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops%20engineer&f_C=2659745",
    },
    {
        "company": "Swiggy",
        "role": "ML Engineer / ML Platform Engineer",
        "category": "Scale-up (Consumer Tech)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python, MLflow, Kubernetes, real-time ranking, feature pipelines, Kafka",
        "why_fit": "Swiggy runs a mature ML platform team (ranking, pricing, ETA models). Your latency/throughput numbers (75% latency cut, 500K req/day) are exactly their scale.",
        "fit_score": 90,
        "priority": "High",
        "primary_link": "https://careers.swiggy.com/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=2417946",
    },
    {
        "company": "ShareChat (Mohalla Tech)",
        "role": "MLOps Engineer / ML Platform Engineer",
        "category": "Scale-up (Consumer Tech)",
        "location": "Bangalore",
        "experience": "1-3 yrs",
        "key_requirements": "Python, K8s, Airflow, model serving (Triton/TorchServe), feature stores",
        "why_fit": "Heaviest ML-as-a-feature company in India (feed ranking, content moderation). Your shadow-deploy framework + observability is exactly what their ML platform team builds.",
        "fit_score": 90,
        "priority": "High",
        "primary_link": "https://sharechat.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops%20OR%20%22ml%20platform%22&f_C=11034301",
    },
    {
        "company": "PhonePe",
        "role": "Software Engineer II (ML Platform / Data Platform)",
        "category": "Scale-up (Fintech)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, Kafka, Airflow, Kubernetes, model serving, observability",
        "why_fit": "Active hiring (160+ open roles April 2026). Fraud/risk + recommendation ML at scale. Your Java + Spring Boot intern experience is a bonus.",
        "fit_score": 88,
        "priority": "High",
        "primary_link": "https://www.phonepe.com/careers/job-openings/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20platform%20OR%20mlops&f_C=2374003",
    },
    {
        "company": "Zomato",
        "role": "Software Engineer (ML Platform / Backend)",
        "category": "Scale-up (Consumer Tech)",
        "location": "Gurgaon",
        "experience": "1-3 yrs",
        "key_requirements": "Python/Go, Kubernetes, real-time inference, feature stores, Kafka",
        "why_fit": "Zomato's ranking, ETA, and pricing ML stack is heavily MLOps-driven. Your inference cost-optimization story (42% infra cut) is highly marketable here.",
        "fit_score": 88,
        "priority": "High",
        "primary_link": "https://www.zomato.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer%20OR%20mlops&f_C=22740",
    },
    {
        "company": "Meesho",
        "role": "Software Engineer (ML / Backend Platform)",
        "category": "Scale-up (E-commerce)",
        "location": "Bangalore",
        "experience": "1-3 yrs",
        "key_requirements": "Python, Kubernetes, ML serving, Kafka, observability, Airflow",
        "why_fit": "29 open positions April 2026. Strong ML platform team (search, ranking, fraud). Your real-time inference + observability work fits cleanly.",
        "fit_score": 87,
        "priority": "High",
        "primary_link": "https://www.meesho.io/jobs",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20OR%20mlops&f_C=18046848",
    },
    {
        "company": "Walmart Global Tech India",
        "role": "Software Engineer III (Data / ML Platform)",
        "category": "MNC",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, Kubernetes, Airflow, Spark, model serving, observability",
        "why_fit": "Massive ML platform team (search, personalization, supply chain). Your scale numbers + Java background land well here.",
        "fit_score": 85,
        "priority": "High",
        "primary_link": "https://tech.walmart.com/content/walmart-global-tech/en_us/careers.html",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20platform%20OR%20mlops&f_C=10685",
    },
    {
        "company": "Flipkart",
        "role": "SDE-1 / SDE-2 (ML Platform / Data Infra)",
        "category": "Scale-up (E-commerce)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, Kubernetes, Kafka, Airflow, Spark, ML serving",
        "why_fit": "Mature ML platform org. Your inference latency + cost-cut wins map directly to their problem space.",
        "fit_score": 85,
        "priority": "High",
        "primary_link": "https://www.flipkartcareers.com/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20platform%20OR%20mlops&f_C=10440",
    },
    {
        "company": "CRED",
        "role": "Backend Engineer / ML Engineer",
        "category": "Scale-up (Fintech)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Kotlin, Kubernetes, real-time ML, Kafka, observability",
        "why_fit": "Strong engineering brand. Risk/credit ML + recommendation systems. Your stack lines up; bar is high but doable.",
        "fit_score": 82,
        "priority": "High",
        "primary_link": "https://careers.cred.club/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer%20OR%20backend&f_C=18002255",
    },
    {
        "company": "Yellow.ai",
        "role": "ML Engineer / MLOps Engineer",
        "category": "Scale-up (AI/Conversational)",
        "location": "Bangalore",
        "experience": "1-3 yrs",
        "key_requirements": "Python, PyTorch/TF, model serving (Triton/ONNX), Kubernetes",
        "why_fit": "Conversational AI startup with heavy MLOps needs. Your ONNX + DistilUSE experience is directly relevant.",
        "fit_score": 82,
        "priority": "High",
        "primary_link": "https://yellow.ai/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops%20OR%20ml%20engineer&f_C=10729811",
    },
    {
        "company": "Fractal Analytics",
        "role": "MLOps Engineer / ML Engineer",
        "category": "Consulting (AI/Analytics)",
        "location": "Bangalore / Mumbai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, Azure/AWS ML, Kubernetes, MLflow, Airflow",
        "why_fit": "Major Fortune-500 ML deployment shop. They actively hire MLOps profiles with your exact stack.",
        "fit_score": 82,
        "priority": "High",
        "primary_link": "https://fractal.wd1.myworkdayjobs.com/Careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops&f_C=4878",
    },
    {
        "company": "Tiger Analytics",
        "role": "ML Engineer / Senior Analyst",
        "category": "Consulting (AI/Analytics)",
        "location": "Bangalore / Chennai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS/Azure ML, Spark, model deployment, MLflow",
        "why_fit": "Heavy MLOps practice servicing Fortune 1000. Your end-to-end production ML credentials are competitive.",
        "fit_score": 80,
        "priority": "High",
        "primary_link": "https://www.tigeranalytics.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer%20OR%20mlops&f_C=2761671",
    },
    {
        "company": "Quantiphi",
        "role": "ML Engineer / MLOps Architect Associate",
        "category": "Consulting (AI/Analytics)",
        "location": "Bangalore / Mumbai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, GCP/AWS ML, Kubernetes, Vertex AI / SageMaker",
        "why_fit": "AI-first digital engineering firm; MLOps is core practice. Strong fit for production ML profiles.",
        "fit_score": 80,
        "priority": "High",
        "primary_link": "https://quantiphi.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops&f_C=415028",
    },
    {
        "company": "Glance / InMobi",
        "role": "ML Engineer (Personalization / Ads ML)",
        "category": "Scale-up (AdTech/Consumer)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python, Kafka, real-time ML, Kubernetes, feature stores",
        "why_fit": "Personalization/feed ML at billion-impression scale. Your feature store (Feast/Redis) work is directly relevant.",
        "fit_score": 80,
        "priority": "High",
        "primary_link": "https://www.inmobi.com/company/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=10673",
    },

    # ============================================================
    # MEDIUM PROBABILITY — adjacent roles, good transfer (65-79)
    # ============================================================
    {
        "company": "Atlassian India",
        "role": "Software Engineer / Backend Engineer",
        "category": "MNC (Product)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Java/Python, AWS, Kubernetes, distributed systems",
        "why_fit": "Top engineering brand, strong early-career pipeline (1000+ open roles India). Your scale + observability story is competitive.",
        "fit_score": 78,
        "priority": "Medium",
        "primary_link": "https://www.atlassian.com/company/careers/all-jobs",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=backend%20OR%20ml&f_C=14888",
    },
    {
        "company": "Postman",
        "role": "Backend Engineer (II)",
        "category": "Scale-up (Dev Tools)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Node.js / Python / Go, AWS, microservices, observability",
        "why_fit": "Strong eng culture; backend + observability skills transfer well. ML platform now also relevant (Postman AI).",
        "fit_score": 76,
        "priority": "Medium",
        "primary_link": "https://www.postman.com/company/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=backend%20engineer&f_C=15184163",
    },
    {
        "company": "Hasura",
        "role": "Backend Engineer / Platform Engineer",
        "category": "Scale-up (Dev Tools)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Haskell/Go/Python, Postgres, Kubernetes, distributed systems",
        "why_fit": "Strong backend brand, growing ML/agent infra (PromptQL). Your Postgres + microservices experience fits.",
        "fit_score": 74,
        "priority": "Medium",
        "primary_link": "https://hasura.io/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=backend&f_C=10982950",
    },
    {
        "company": "Microsoft IDC",
        "role": "Software Engineer 2 (Azure ML / AI Platform)",
        "category": "MNC",
        "location": "Bangalore / Hyderabad",
        "experience": "2-5 yrs",
        "key_requirements": "Python/C#, Azure, Kubernetes, distributed ML systems",
        "why_fit": "Active 2026 ML platform hiring (Azure ML, Copilot stack). Your K8s + observability + ML serving is directly applicable.",
        "fit_score": 78,
        "priority": "Medium",
        "primary_link": "https://careers.microsoft.com/v2/global/en/locations/india.html",
        "search_link": "https://jobs.careers.microsoft.com/global/en/search?lc=India&p=Software%20Engineering&exp=Experienced%20professionals",
    },
    {
        "company": "Adobe India",
        "role": "ML Engineer / SDE (Adobe Experience Platform)",
        "category": "MNC",
        "location": "Bangalore / Noida",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java/Scala, Spark, Kubernetes, ML serving",
        "why_fit": "AEP has heavy ML personalization stack. Your production ML + Java background is competitive.",
        "fit_score": 76,
        "priority": "Medium",
        "primary_link": "https://careers.adobe.com/us/en/c/india-jobs",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=1824",
    },
    {
        "company": "Salesforce India",
        "role": "Member of Technical Staff (MTS) - Einstein / AI Platform",
        "category": "MNC",
        "location": "Bangalore / Hyderabad",
        "experience": "2-4 yrs",
        "key_requirements": "Java/Python, AWS, Kubernetes, distributed ML",
        "why_fit": "Einstein AI Platform is core focus. Strong fit for production ML profiles; bar is high but achievable.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://careers.salesforce.com/en/jobs/?search=&country=India",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mts%20OR%20software%20engineer&f_C=3185",
    },
    {
        "company": "Intuit India",
        "role": "Software Engineer 2 / SDE 2 (Data / ML Platform)",
        "category": "MNC",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, AWS, Kubernetes, data pipelines",
        "why_fit": "Strong data/ML platform team; risk/fraud ML matches your fintech (KaveoSoft EFT) background.",
        "fit_score": 75,
        "priority": "Medium",
        "primary_link": "https://www.intuit.com/careers/programs/india/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=3257",
    },
    {
        "company": "Amazon India (AWS / Alexa AI)",
        "role": "SDE-1 / SDE-2 (ML Platform / Personalization)",
        "category": "MNC",
        "location": "Bangalore / Hyderabad",
        "experience": "2-4 yrs",
        "key_requirements": "Java/Python, AWS (SageMaker, EKS), distributed systems",
        "why_fit": "Many ML platform teams (SageMaker, Bedrock, ranking). Bar raiser is hard but profile is competitive.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.amazon.jobs/en/locations/bangalore-india",
        "search_link": "https://www.amazon.jobs/en/search?base_query=ml+engineer&loc_query=India",
    },
    {
        "company": "Tredence",
        "role": "ML Engineer / MLOps Engineer",
        "category": "Consulting (AI/Analytics)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python, Azure/AWS, Databricks, MLflow",
        "why_fit": "Growing MLOps practice; your end-to-end production credentials are above the bar here.",
        "fit_score": 78,
        "priority": "Medium",
        "primary_link": "https://www.tredence.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops&f_C=687823",
    },
    {
        "company": "ZS Associates",
        "role": "Decision Analytics Associate / ML Engineer",
        "category": "Consulting",
        "location": "Bangalore / Pune / Gurgaon",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS, Snowflake, ML deployment",
        "why_fit": "Pharma/healthcare analytics; growing MLOps charter. Solid resume bump even if domain shift.",
        "fit_score": 70,
        "priority": "Medium",
        "primary_link": "https://www.zs.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=4123",
    },
    {
        "company": "Affine",
        "role": "Senior ML Engineer / Data Scientist",
        "category": "Consulting (AI/Analytics)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS/Azure, ML deployment, MLOps tooling",
        "why_fit": "Mid-size analytics firm with active MLOps hiring. Your scale numbers stand out.",
        "fit_score": 74,
        "priority": "Medium",
        "primary_link": "https://affine.ai/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mlops%20OR%20ml%20engineer&f_C=2444041",
    },
    {
        "company": "LatentView Analytics",
        "role": "Senior Analyst / ML Engineer",
        "category": "Consulting (AI/Analytics)",
        "location": "Chennai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS, Spark, ML deployment",
        "why_fit": "Public analytics firm; growing MLOps practice. Reasonable jump if open to Chennai.",
        "fit_score": 70,
        "priority": "Medium",
        "primary_link": "https://www.latentview.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=240658",
    },
    {
        "company": "Acko",
        "role": "Backend Engineer / Data Engineer",
        "category": "Scale-up (Insurtech)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, AWS, Kafka, distributed systems",
        "why_fit": "Risk/fraud ML in insurance. Your fintech backend + ML credentials transfer well.",
        "fit_score": 76,
        "priority": "Medium",
        "primary_link": "https://www.acko.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=backend%20OR%20ml&f_C=10693825",
    },
    {
        "company": "Cars24",
        "role": "ML Engineer / Backend Engineer",
        "category": "Scale-up (Auto)",
        "location": "Gurgaon",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS, Kubernetes, ML pipelines",
        "why_fit": "Pricing + recommendation ML. Your real-time inference experience is directly applicable.",
        "fit_score": 74,
        "priority": "Medium",
        "primary_link": "https://www.cars24.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=10727876",
    },
    {
        "company": "Nykaa",
        "role": "Backend / ML Engineer",
        "category": "Scale-up (E-commerce)",
        "location": "Mumbai / Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, AWS, recommendation ML, microservices",
        "why_fit": "Search + recommendations ML team. Reasonable transfer with your stack.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.nykaa.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=2697158",
    },
    {
        "company": "Bajaj Finserv (Bajaj Markets / Allianz Tech)",
        "role": "ML Engineer / Data Scientist",
        "category": "Non-tech (BFSI)",
        "location": "Pune",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS/Azure, ML deployment, fraud/credit models",
        "why_fit": "Heavy ML investment (credit, fraud). Your real-time risk-scoring project is directly relevant.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.bajajfinserv.in/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=4949",
    },
    {
        "company": "HDFC Bank",
        "role": "Data Scientist / ML Engineer (Centralized Data Science Group)",
        "category": "Non-tech (BFSI)",
        "location": "Mumbai / Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python, SAS/SQL, ML deployment, banking domain bonus",
        "why_fit": "Centralized DS team actively hiring (74+ data jobs April 2026). Risk/fraud ML stack matches your project.",
        "fit_score": 70,
        "priority": "Medium",
        "primary_link": "https://www.hdfcbank.com/personal/about-us/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=data%20scientist%20OR%20ml%20engineer&f_C=2003810",
    },
    {
        "company": "ICICI Bank",
        "role": "Decision Sciences / ML Engineer",
        "category": "Non-tech (BFSI)",
        "location": "Mumbai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, SQL, ML modeling, deployment",
        "why_fit": "Decision sciences group hires production ML profiles. Domain shift but your stack is portable.",
        "fit_score": 67,
        "priority": "Medium",
        "primary_link": "https://careers.icicibank.com/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=1782",
    },
    {
        "company": "Tata Digital",
        "role": "ML Engineer / Backend Engineer",
        "category": "Non-tech (Conglomerate)",
        "location": "Bangalore / Mumbai",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, AWS, microservices, ML serving",
        "why_fit": "Tata Neu super-app needs heavy ML platform investment. Strong fit for production ML profiles.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.tatadigital.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=72780497",
    },
    {
        "company": "Reliance Jio Platforms",
        "role": "Software Engineer (AI/ML / Data Platform)",
        "category": "Non-tech (Telecom)",
        "location": "Mumbai / Bangalore / Hyderabad",
        "experience": "1-4 yrs",
        "key_requirements": "Python/Java, big data, Kafka, ML deployment",
        "why_fit": "9000+ openings in 2026 recruitment drive. Reasonable transfer; pay/brand mid-tier.",
        "fit_score": 68,
        "priority": "Medium",
        "primary_link": "https://careers.jio.com/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=2374090",
    },
    {
        "company": "Bharti Airtel (Airtel X Labs / Airtel Digital)",
        "role": "ML Engineer / Backend Engineer",
        "category": "Non-tech (Telecom)",
        "location": "Gurgaon / Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS/GCP, Kafka, ML serving",
        "why_fit": "Heavy churn-prediction + recommendation ML. Reasonable transfer.",
        "fit_score": 68,
        "priority": "Medium",
        "primary_link": "https://www.airtel.in/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=2192",
    },
    {
        "company": "Browserstack",
        "role": "Backend Engineer / SRE",
        "category": "Scale-up (Dev Tools)",
        "location": "Mumbai (hybrid)",
        "experience": "2-4 yrs",
        "key_requirements": "Ruby/Python, AWS, Kubernetes, observability",
        "why_fit": "Strong eng brand, observability/SRE skills directly transfer. ML now also a focus area.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.browserstack.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=backend%20OR%20sre&f_C=1236337",
    },
    {
        "company": "Freshworks",
        "role": "Backend / ML Engineer (Freddy AI)",
        "category": "Scale-up (SaaS)",
        "location": "Chennai / Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Ruby, AWS, ML serving, microservices",
        "why_fit": "Freddy AI platform expanding. Reasonable fit for ML+backend profile.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.freshworks.com/company/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20OR%20backend&f_C=224337",
    },
    {
        "company": "Plivo",
        "role": "Backend / Platform Engineer",
        "category": "Scale-up (CPaaS)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Go, AWS, Kubernetes, distributed systems",
        "why_fit": "Strong eng brand; messaging platform with growing ML (spam/fraud detection).",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.plivo.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=backend%20engineer&f_C=246030",
    },
    {
        "company": "Slice",
        "role": "Backend / ML Engineer",
        "category": "Scale-up (Fintech)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Kotlin, AWS, Kafka, ML serving",
        "why_fit": "Credit/risk ML stack. Direct fit with your fintech + risk-scoring background.",
        "fit_score": 78,
        "priority": "Medium",
        "primary_link": "https://www.sliceit.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20OR%20backend&f_C=18078432",
    },
    {
        "company": "Setu",
        "role": "Software Engineer (Backend / Platform)",
        "category": "Scale-up (Fintech API)",
        "location": "Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Go, Postgres, AWS, Kubernetes",
        "why_fit": "Embedded finance API platform; fintech backend bar matches you well.",
        "fit_score": 74,
        "priority": "Medium",
        "primary_link": "https://setu.co/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=backend%20engineer&f_C=18205867",
    },
    {
        "company": "M2P Fintech",
        "role": "Backend / ML Engineer",
        "category": "Scale-up (Fintech API)",
        "location": "Chennai / Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, microservices, AWS, ML deployment",
        "why_fit": "Fast-growing card-issuance + lending stack. Reasonable fit.",
        "fit_score": 70,
        "priority": "Medium",
        "primary_link": "https://m2pfintech.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20OR%20backend&f_C=1463145",
    },
    {
        "company": "Mad Street Den (Vue.ai)",
        "role": "ML Engineer / MLOps Engineer",
        "category": "Scale-up (AI/Retail)",
        "location": "Chennai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, PyTorch/TF, Kubernetes, model serving",
        "why_fit": "Computer-vision + retail AI; MLOps culture mature. Strong fit if open to Chennai.",
        "fit_score": 76,
        "priority": "Medium",
        "primary_link": "https://www.madstreetden.com/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer%20OR%20mlops&f_C=2906033",
    },
    {
        "company": "Gupshup",
        "role": "Backend / ML Engineer",
        "category": "Scale-up (Conv AI)",
        "location": "Bangalore / Mumbai",
        "experience": "2-4 yrs",
        "key_requirements": "Python/Java, AWS, Kafka, ML serving",
        "why_fit": "Conversational AI platform; ML serving + observability needs match yours.",
        "fit_score": 72,
        "priority": "Medium",
        "primary_link": "https://www.gupshup.io/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20OR%20backend&f_C=5378",
    },
    {
        "company": "Haptik (Jio)",
        "role": "ML Engineer / Backend Engineer",
        "category": "Scale-up (Conv AI)",
        "location": "Mumbai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, PyTorch, AWS, model serving",
        "why_fit": "Conversational AI; production ML serving is core. Reasonable fit.",
        "fit_score": 70,
        "priority": "Medium",
        "primary_link": "https://haptik.ai/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=2832697",
    },
    {
        "company": "Oracle India / Oracle Cloud",
        "role": "Software Engineer 3 / Member of Technical Staff",
        "category": "MNC",
        "location": "Bangalore / Hyderabad",
        "experience": "2-5 yrs",
        "key_requirements": "Java/Python, OCI, Kubernetes, distributed systems",
        "why_fit": "OCI Data Science / AI Services hiring; PL/SQL + Java background gives you an edge.",
        "fit_score": 70,
        "priority": "Medium",
        "primary_link": "https://www.oracle.com/in/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=mts%20OR%20software%20engineer&f_C=1028",
    },
    {
        "company": "VMware (Broadcom) India",
        "role": "Software Engineer (ML / Platform)",
        "category": "MNC",
        "location": "Bangalore / Pune",
        "experience": "2-4 yrs",
        "key_requirements": "Go/Python/Java, Kubernetes, distributed systems",
        "why_fit": "Tanzu / VCF MLOps stack. K8s expertise transfers cleanly.",
        "fit_score": 68,
        "priority": "Medium",
        "primary_link": "https://careers.broadcom.com/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=165158",
    },

    # ============================================================
    # STRETCH — top-tier brand or higher bar (50-64)
    # ============================================================
    {
        "company": "Google India",
        "role": "Software Engineer III (Early Career — ML / SWE)",
        "category": "MNC (Top-tier)",
        "location": "Bangalore / Hyderabad",
        "experience": "2-5 yrs",
        "key_requirements": "C++/Python/Java, distributed systems, strong DSA",
        "why_fit": "Brand stretch; bar is high (DSA-heavy). Worth applying — your scale story helps.",
        "fit_score": 62,
        "priority": "Stretch",
        "primary_link": "https://www.google.com/about/careers/applications/jobs/results/?location=India",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=1441",
    },
    {
        "company": "Meta India",
        "role": "Software Engineer / ML Engineer",
        "category": "MNC (Top-tier)",
        "location": "Hyderabad / Bangalore (limited)",
        "experience": "2-5 yrs",
        "key_requirements": "Python/C++/PHP, distributed systems, ML at scale",
        "why_fit": "Limited India headcount but actively hiring ML platform. Bar is high.",
        "fit_score": 58,
        "priority": "Stretch",
        "primary_link": "https://www.metacareers.com/jobs?offices[0]=Bengaluru%2C%20India&offices[1]=Hyderabad%2C%20India",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=10667",
    },
    {
        "company": "Nvidia India",
        "role": "DGX Cloud / ML Systems Engineer",
        "category": "MNC (Top-tier AI)",
        "location": "Bangalore / Pune",
        "experience": "2-5 yrs",
        "key_requirements": "Python/C++/CUDA, Kubernetes, model serving, GPU systems",
        "why_fit": "GPU-to-CPU optimization story is interesting here, but most roles want CUDA depth.",
        "fit_score": 60,
        "priority": "Stretch",
        "primary_link": "https://www.nvidia.com/en-in/about-nvidia/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20systems&f_C=3608",
    },
    {
        "company": "McKinsey QuantumBlack",
        "role": "Data Engineer / ML Engineer Associate",
        "category": "Consulting (Top-tier)",
        "location": "Bangalore / Gurgaon",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS/Azure, MLflow, Spark, client-facing skills",
        "why_fit": "Top brand stretch. Production ML credentials help; consulting communication bar is the gating factor.",
        "fit_score": 64,
        "priority": "Stretch",
        "primary_link": "https://www.mckinsey.com/careers/search-jobs/jobs?keywords=quantumblack&country=India",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=quantumblack&f_C=1371",
    },
    {
        "company": "BCG X (formerly BCG Gamma)",
        "role": "Data Engineer / ML Engineer",
        "category": "Consulting (Top-tier)",
        "location": "Bangalore / Gurgaon",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS/Azure, MLflow, client delivery",
        "why_fit": "Top brand stretch; bar is comparable to QuantumBlack.",
        "fit_score": 62,
        "priority": "Stretch",
        "primary_link": "https://careers.bcg.com/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=bcg%20x%20OR%20gamma&f_C=4915",
    },
    {
        "company": "Bain Capability Network (Vector)",
        "role": "Specialist - Advanced Analytics",
        "category": "Consulting (Top-tier)",
        "location": "Gurgaon / Bangalore",
        "experience": "2-4 yrs",
        "key_requirements": "Python, ML modeling, client-facing analytics",
        "why_fit": "Stretch — more analytics-leaning than MLOps. Brand bump if shortlisted.",
        "fit_score": 58,
        "priority": "Stretch",
        "primary_link": "https://www.bain.com/careers/",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=bain%20capability%20network&f_C=1701",
    },
    {
        "company": "Accenture AI Refinery / Accenture Strategy",
        "role": "ML Engineer / AI Specialist",
        "category": "Consulting",
        "location": "Bangalore / Hyderabad / Pune",
        "experience": "2-4 yrs",
        "key_requirements": "Python, cloud ML (AWS/Azure/GCP), MLflow",
        "why_fit": "Volume hiring; pay below product co's but easy access. Use as backup.",
        "fit_score": 62,
        "priority": "Stretch",
        "primary_link": "https://www.accenture.com/in-en/careers",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer%20OR%20mlops&f_C=1033",
    },
    {
        "company": "Deloitte AI Institute / Deloitte Digital",
        "role": "Consultant / Senior Consultant (AI/ML)",
        "category": "Consulting",
        "location": "Bangalore / Hyderabad / Mumbai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, Azure/AWS ML, client delivery",
        "why_fit": "Volume hiring; useful as a brand fallback. Less hands-on MLOps than analytics.",
        "fit_score": 60,
        "priority": "Stretch",
        "primary_link": "https://www2.deloitte.com/in/en/careers.html",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=1038",
    },
    {
        "company": "Goldman Sachs India (Engineering Division)",
        "role": "Software Engineer (Marquee / Risk / ML platforms)",
        "category": "Non-tech (BFSI / Investment Banking)",
        "location": "Bangalore / Hyderabad",
        "experience": "2-4 yrs",
        "key_requirements": "Java/Python, distributed systems, low-latency",
        "why_fit": "High bar; risk/quant platform engineering. Your real-time scoring + observability work fits the narrative.",
        "fit_score": 60,
        "priority": "Stretch",
        "primary_link": "https://www.goldmansachs.com/careers/students/programs/india/full-time-analyst.html",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=1382",
    },
    {
        "company": "JPMorgan Chase India (Corporate & Investment Bank Tech)",
        "role": "Software Engineer (ML / Risk Tech)",
        "category": "Non-tech (BFSI)",
        "location": "Mumbai / Bangalore / Hyderabad",
        "experience": "2-4 yrs",
        "key_requirements": "Java/Python, AWS, Kafka, ML deployment",
        "why_fit": "Strong ML/risk tech in India. Reasonable bar; brand bump.",
        "fit_score": 64,
        "priority": "Stretch",
        "primary_link": "https://careers.jpmorgan.com/global/en/students/programs/asia-pacific",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=software%20engineer&f_C=1118",
    },
    {
        "company": "Standard Chartered (SCB GBS)",
        "role": "ML Engineer / Data Scientist",
        "category": "Non-tech (BFSI)",
        "location": "Bangalore / Chennai",
        "experience": "2-4 yrs",
        "key_requirements": "Python, AWS/Azure, ML deployment, banking domain",
        "why_fit": "Banking-tech with growing ML platform; reasonable transfer.",
        "fit_score": 62,
        "priority": "Stretch",
        "primary_link": "https://scb.taleo.net/careersection/ex/jobsearch.ftl",
        "search_link": "https://www.linkedin.com/jobs/search/?keywords=ml%20engineer&f_C=2412",
    },
]


def by_priority(priority: str):
    """Filter jobs by priority bucket."""
    return sorted(
        [j for j in JOBS if j["priority"] == priority],
        key=lambda j: j["fit_score"],
        reverse=True,
    )


def all_sorted():
    """All jobs sorted by fit score descending."""
    return sorted(JOBS, key=lambda j: j["fit_score"], reverse=True)
